name: Build and SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov tox
          pip install -r requirements.txt || echo "No requirements.txt found"
          
      - name: Run tests and generate coverage
        run: |
          pytest --cov=. --cov-report=xml --cov-report=term
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-scan-action@v1.9  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}